### ISSUE TITLE
Supporting nil value

### ISSUE THREAD

**Issue by lkzhao** [christophhagen/BinaryCodable#4]
I ran into this error when trying to encode an struct with an optional value. Does the library support nil value encoding?

<img width="753" alt="Screen Shot 2022-08-28 at 8 58 07 AM" src="https://user-images.githubusercontent.com/3359850/187083239-08116ee4-9cf8-46ea-9df6-8c0f77f0a746.png">

**Comment by christophhagen** [comment]
Optionals are supported.

Can you share your struct definition so that I can try to reproduce the error?
