### ISSUE TITLE
Documentation on BinaryStreamDecoder is out of date

### ISSUE THREAD

**Issue by hogliux** [christophhagen/BinaryCodable#8]
Thank you so much for this great utility. It works super well so far.

However, documentation on BinaryStreamDecoder seems a bit out-of-date:

https://github.com/christophhagen/BinaryCodable/blob/28804e7ffb656e53949cb0713691fb53aed26fe1/Sources/BinaryCodable/BinaryStreamDecoder.swift#L10

**Comment by christophhagen** [comment]
Thanks for the info.

I've updated the relevant text with commit [97d257c](https://github.com/christophhagen/BinaryCodable/commit/97d257cdba3bc3e5101bbe6243f1c8b3e6b08e9c), and added a few more features to the stream decoder. These will be in the next release.

**Comment by hogliux** [comment]
Thank you!
